import type { Metadata } from "next";
import "./globals.css";
import { v4 } from "uuid";
import getUser from "@/utils/getUser";
import AppProvider from "./AppProvider";

export const metadata: Metadata = {
  title: "Desafio Atom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  // Cria automaticamente um uuid pro usuário, sem a necessidade de um login
  const uuid = v4();
  const userId = getUser() ?? uuid;

  return (
    <html lang="pt-br" className="scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&display=swap" rel="stylesheet"/>
      </head>
      <body className="w-full min-h-screen flex flex-col">
        <AppProvider uuid={userId}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
